# This is a basic workflow to help you get started with Actions

name: First Workflow

# Controls when the workflow will run
on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Print greeting
        run: echo Hello, World!

      - name: Format
        run: npm run format

      - name: Print goodbye
        run: echo Bye!
