# This is a basic workflow to help you get started with Actions

name: First Workflow

# Controls when the workflow will run
on:
#  # Triggers the workflow on push or pull request events but only for the "main" branch
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
  workflow_dispatch:

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Print greeting
        run: echo Hello, World!

      - name: Print goodbye
        run: echo Bye!
