name: Second Workflow

on:
  push
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  second-job:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install angular-cli globally
        run: npm install -g @angular/cli@~16.2.2

      - name: Install npm dependencies
        run: npm ci

      - name: Check code formatting
        run: npm run format

      - name: Run tests with coverage
        run: ng test --browsers ChromeHeadless --code-coverage --watch=false
